name: mask

on:
  push:
    branches:
      - workflow_08

env:
  password: pass@123

jobs:
  mask:
    runs-on: ubuntu-latest

    steps:
      - name: step_1
        run: echo "$password"
      - name: step_2
        run: echo "::add-mask::$password"
