name: needs

on:
  push:
    branches:
      - workflow_04

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: job_1-1
        run: echo "job_1-1"
      - name: job_1-2
        run: echo "job_1-2"
  job_2:
    runs-on: ubuntu-latest
    needs: jpb_3
    steps:
      - name: job_2-1
        run: echo "job_2-1"
  job_3:
    runs-on: ubuntu-latest
    needs: jpb_1
    steps:
      - name: job_3-1
        run: echo "job_3-1"
      - name: job_3-2
        run: echo "job_3-2"
