name: 実行順序制御

on:
  push:
    branches:
      - workflow_04

jobs:
  context-and-env:
    runs-on: ubuntu-latest
    steps:
      job_1:
        name: job name 1
        run: echo "JOB_1"
      job_2:
        name: job name 2
        run: echo "JOB_2"
        needs: job_3
      job_3:
        name: job name 3
        run: echo "JOB_3"
        needs: job_1
      job_4:
        name: job name 4
        run: echo "JOB_4"
        needs: job_2
